#!/bin/bash

# Set the output file
OUTPUT_FILE="./README.md"

# Function to check if terraform-docs is installed
check_terraform_docs() {
    if ! command -v terraform-docs &> /dev/null; then
        echo "terraform-docs could not be found. Please install it first."
        exit 1
    fi
}

# Function to generate documentation
generate_docs() {
    echo "Generating Terraform documentation..."

    # Generate the documentation
    terraform-docs markdown . --output-file "$OUTPUT_FILE"

    if [ $? -eq 0 ]; then
        echo "Documentation generated successfully at $OUTPUT_FILE."
    else
        echo "Failed to generate documentation."
        exit 1
    fi
}

# Main script execution
check_terraform_docs
generate_docs
